config/routes.rb
NewMeetme::Application.routes.draw do
  resources :messages

  resources :locations

  resources :profiles
    match 'profile/create/' => 'profiles#create'
    match 'profile/:id/update_interests' => 'profiles#update_interests'
    match 'profile/:id/update_location' => 'profiles#update_location'
    match 'profile/:id/match' => 'profiles#match'
  resources :interests

  resources :matchings

  resources :biographies
    match 'biographies/user/:user_id' => 'biographies#show'

  resources :users
    match 'users/:id/username' => 'users#username'
    match 'users/:id/name' => 'users#name'
    match 'users/:id/email' => 'users#email'
    match 'users/:id/photo' => 'users#photo'

  root :to => "users#index"

end

app/models/message.rb
class Message < ActiveRecord::Base
  include Rhoconnect::Resource

  attr_accessible :message, :recipient_deleted, :recipient_id, :user_deleted, :user_id
  belongs_to :user
  belongs_to :recipient, :class_name => "User"

  def partition 
    lambda { self.user.username }
  end

  def self.rhoconnect_query(partition)
    user = User.find_by_email(partition)
    Message.where("(user_id = ? OR recipient_id = ?)", user.id.to_s, user.id.to_s)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :recipient_id %><br />
    <%= f.number_field :recipient_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :user_deleted %><br />
    <%= f.check_box :user_deleted %>
  </div>
  <div class="field">
    <%= f.label :recipient_deleted %><br />
    <%= f.check_box :recipient_deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>User</th>
    <th>Recipient</th>
    <th>Message</th>
    <th>User deleted</th>
    <th>Recipient deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.user_id %></td>
    <td><%= message.recipient_id %></td>
    <td><%= message.message %></td>
    <td><%= message.user_deleted %></td>
    <td><%= message.recipient_deleted %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @message.user_id %>
</p>

<p>
  <b>Recipient:</b>
  <%= @message.recipient_id %>
</p>

<p>
  <b>Message:</b>
  <%= @message.message %>
</p>

<p>
  <b>User deleted:</b>
  <%= @message.user_deleted %>
</p>

<p>
  <b>Recipient deleted:</b>
  <%= @message.recipient_deleted %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>