config/routes.rb
NewMeetme::Application.routes.draw do
  resources :messages

  resources :locations

  resources :profiles
    match 'profile/create/' => 'profiles#create'
    match 'profile/:id/update_interests' => 'profiles#update_interests'
    match 'profile/:id/update_location' => 'profiles#update_location'
    match 'profile/:id/match' => 'profiles#match'
  resources :interests

  resources :matchings

  resources :biographies
    match 'biographies/user/:user_id' => 'biographies#show'

  resources :users
    match 'users/:id/username' => 'users#username'
    match 'users/:id/name' => 'users#name'
    match 'users/:id/email' => 'users#email'
    match 'users/:id/photo' => 'users#photo'

  root :to => "users#index"

end

app/models/biography.rb
class Biography < ActiveRecord::Base
  include Rhoconnect::Resource
  belongs_to :user
  has_many :images
  validates_presence_of :birthday
  attr_accessible :about, :birthday, :occupation, :photo, :user_id

  def partition 
    lambda { self.user.username }
  end

  def self.rhoconnect_query(partition)
    user = User.find_by_email(partition)
    Biography.where(:user_id => user.id)
  end
end

app/controllers/biographies_controller.rb
class BiographiesController < ApplicationController
  # GET /biographies
  # GET /biographies.json
  def index
    @biographies = Biography.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @biographies }
    end
  end

  # GET /biographies/1
  # GET /biographies/1.json
  # Get /biogrpahies/user.json/?user_id=1
  def show
    if params[:user_id]
      @biography = Biography.find_by_user_id(params[:user_id])
    else
      @biography = Biography.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @biography }
    end
  end

  # GET /biographies/new
  # GET /biographies/new.json
  def new
    @biography = Biography.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @biography }
    end
  end

  # GET /biographies/1/edit
  def edit
    @biography = Biography.find(params[:id])
  end

  # POST /biographies
  # POST /biographies.json
  def create
    @biography = Biography.new(params[:biography])

    respond_to do |format|
      if @biography.save
        format.html { redirect_to @biography, notice: 'Biography was successfully created.' }
        format.json { render json: @biography, status: :created, location: @biography }
      else
        format.html { render action: "new" }
        format.json { render json: @biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /biographies/1
  # PUT /biographies/1.json
  def update
    @biography = Biography.find(params[:id])

    respond_to do |format|
      if @biography.update_attributes(params[:biography])
        format.html { redirect_to @biography, notice: 'Biography was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biographies/1
  # DELETE /biographies/1.json
  def destroy
    @biography = Biography.find(params[:id])
    @biography.destroy

    respond_to do |format|
      format.html { redirect_to biographies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/biographies_helper.rb
module BiographiesHelper
end

app/views/biographies/_form.html.erb
<%= form_for(@biography) do |f| %>
  <% if @biography.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@biography.errors.count, "error") %> prohibited this biography from being saved:</h2>

      <ul>
      <% @biography.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :about %><br />
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday, :start_year => 1950 %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br />
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/biographies/edit.html.erb
<h1>Editing biography</h1>

<%= render 'form' %>

<%= link_to 'Show', @biography %> |
<%= link_to 'Back', biographies_path %>

app/views/biographies/index.html.erb
<h1>Listing biographies</h1>

<table>
  <tr>
    <th>About</th>
    <th>Birthday</th>
    <th>Occupation</th>
    <th>Photo</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @biographies.each do |biography| %>
  <tr>
    <td><%= biography.about %></td>
    <td><%= biography.birthday %></td>
    <td><%= biography.occupation %></td>
    <td><%= biography.photo %></td>
    <td><%= biography.user %></td>
    <td><%= link_to 'Show', biography %></td>
    <td><%= link_to 'Edit', edit_biography_path(biography) %></td>
    <td><%= link_to 'Destroy', biography, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Biography', new_biography_path %>

app/views/biographies/new.html.erb
<h1>New biography</h1>

<%= render 'form' %>

<%= link_to 'Back', biographies_path %>

app/views/biographies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>About:</b>
  <%= @biography.about %>
</p>

<p>
  <b>Birthday:</b>
  <%= @biography.birthday %>
</p>

<p>
  <b>Occupation:</b>
  <%= @biography.occupation %>
</p>

<p>
  <b>Photo:</b>
  <%= @biography.photo %>
</p>

<p>
  <b>User:</b>
  <%= @biography.user %>
</p>


<%= link_to 'Edit', edit_biography_path(@biography) %> |
<%= link_to 'Back', biographies_path %>