config/routes.rb
NewMeetme::Application.routes.draw do
  resources :messages

  resources :locations

  resources :profiles
    match 'profile/create/' => 'profiles#create'
    match 'profile/:id/update_interests' => 'profiles#update_interests'
    match 'profile/:id/update_location' => 'profiles#update_location'
    match 'profile/:id/match' => 'profiles#match'
  resources :interests

  resources :matchings

  resources :biographies
    match 'biographies/user/:user_id' => 'biographies#show'

  resources :users
    match 'users/:id/username' => 'users#username'
    match 'users/:id/name' => 'users#name'
    match 'users/:id/email' => 'users#email'
    match 'users/:id/photo' => 'users#photo'

  root :to => "users#index"

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  include Rhoconnect::Resource

  attr_accessible :name

  has_and_belongs_to_many :users

  def partition
    lambda { self.user.username }
  end

  def self.rhoconnect_query(partition)
    user = User.find_by_email(partition)
    user.interests
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.find(:all, :order=> "name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interests }
    end
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
    @interest = Interest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interest }
    end
  end

  # GET /interests/new
  # GET /interests/new.json
  def new
    @interest = Interest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interest }
    end
  end

  # GET /interests/1/edit
  def edit
    @interest = Interest.find(params[:id])
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(params[:interest])

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render json: @interest, status: :created, location: @interest }
      else
        format.html { render action: "new" }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interests/1
  # PUT /interests/1.json
  def update
    @interest = Interest.find(params[:id])

    respond_to do |format|
      if @interest.update_attributes(params[:interest])
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest = Interest.find(params[:id])
    @interest.destroy

    respond_to do |format|
      format.html { redirect_to interests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_form.html.erb
<%= form_for(@interest) do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% @interest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interests/edit.html.erb
<h1>Editing interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

app/views/interests/index.html.erb
<h1>Listing interests</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interests.each do |interest| %>
  <tr>
    <td><%= interest.name %></td>
    <td><%= link_to 'Show', interest %></td>
    <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
    <td><%= link_to 'Destroy', interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interest', new_interest_path %>

app/views/interests/new.html.erb
<h1>New interest</h1>

<%= render 'form' %>

<%= link_to 'Back', interests_path %>

app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @interest.name %>
</p>


<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>